"""Update migration

Revision ID: 0bb63001cfe2
Revises: f83f2db62ecb
Create Date: 2021-02-09 10:01:38.603671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bb63001cfe2'
down_revision = 'f83f2db62ecb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier', sa.Column('fax_number', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplier', 'fax_number')
    # ### end Alembic commands ###
