"""Update migration

Revision ID: 19c78ad5ba82
Revises: 753be1d48196
Create Date: 2021-02-18 09:06:39.073611

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '19c78ad5ba82'
down_revision = '753be1d48196'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory')
    op.add_column('inware_list', sa.Column('notes', sa.String(length=255), nullable=True))
    op.add_column('inware_list', sa.Column('total_amount', sa.Numeric(), nullable=False))
    op.drop_column('inware_list', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inware_list', sa.Column('description', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=True))
    op.drop_column('inware_list', 'total_amount')
    op.drop_column('inware_list', 'notes')
    op.create_table('inventory',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('time_span', mysql.DATETIME(), nullable=False),
    sa.Column('created_on', mysql.DATETIME(), nullable=False),
    sa.Column('updated_on', mysql.DATETIME(), nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='inventory_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
