"""Update migration

Revision ID: 20ac1129beb2
Revises: 33c07daad86d
Create Date: 2020-12-22 14:14:51.689257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20ac1129beb2'
down_revision = '33c07daad86d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('other_fees', sa.Column('amount', sa.Numeric(), nullable=False))
    op.drop_index('email', table_name='supplier')
    op.drop_index('phone_number', table_name='supplier')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('phone_number', 'supplier', ['phone_number'], unique=True)
    op.create_index('email', 'supplier', ['email'], unique=True)
    op.drop_column('other_fees', 'amount')
    # ### end Alembic commands ###
