"""Update migration

Revision ID: 411b190987bd
Revises: 4740edf913b9
Create Date: 2020-11-30 15:47:00.288706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '411b190987bd'
down_revision = '4740edf913b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_category', sa.Column('parent_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_category', 'parent_id')
    # ### end Alembic commands ###
