"""Update migration

Revision ID: 417495976685
Revises: 151de6974fbb
Create Date: 2021-01-30 19:49:20.241902

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '417495976685'
down_revision = '151de6974fbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_log')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_log',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('quantity', mysql.DECIMAL(precision=10, scale=0), nullable=False),
    sa.Column('created_on', mysql.DATETIME(), nullable=False),
    sa.Column('updated_on', mysql.DATETIME(), nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('original_price', mysql.DECIMAL(precision=10, scale=0), nullable=False),
    sa.Column('sale_price', mysql.DECIMAL(precision=10, scale=0), nullable=False),
    sa.Column('recorded_date', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='product_log_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
