"""Update Migration

Revision ID: 4740edf913b9
Revises: 4375a426efbc
Create Date: 2020-11-10 15:20:01.553690

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4740edf913b9'
down_revision = '4375a426efbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_price_history', sa.Column('effective_date', sa.DateTime(), nullable=False))
    op.drop_column('product_price_history', 'price_updated_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_price_history', sa.Column('price_updated_date', mysql.DATETIME(), nullable=False))
    op.drop_column('product_price_history', 'effective_date')
    # ### end Alembic commands ###
