"""Update Migration

Revision ID: 49204d20dff2
Revises: 411b190987bd
Create Date: 2020-12-02 15:14:36.290054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49204d20dff2'
down_revision = '411b190987bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_category', sa.Column('parent_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_category', 'parent_id')
    # ### end Alembic commands ###
