"""Update migration

Revision ID: 51a2a7b48da7
Revises: 0bb63001cfe2
Create Date: 2021-02-12 22:30:38.909333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51a2a7b48da7'
down_revision = '0bb63001cfe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manufacturer', sa.Column('address', sa.String(length=255), nullable=False))
    op.add_column('manufacturer', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('manufacturer', sa.Column('fax_number', sa.String(length=255), nullable=False))
    op.add_column('manufacturer', sa.Column('phone_number', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manufacturer', 'phone_number')
    op.drop_column('manufacturer', 'fax_number')
    op.drop_column('manufacturer', 'email')
    op.drop_column('manufacturer', 'address')
    # ### end Alembic commands ###
