"""Update migration

Revision ID: 51f4af90bb15
Revises: f4e8eee02351
Create Date: 2021-02-17 09:00:52.882870

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '51f4af90bb15'
down_revision = 'f4e8eee02351'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.String(length=255), nullable=False))
    op.add_column('user', sa.Column('created_on', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('date_of_birth', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('full_name', sa.String(length=100), nullable=False))
    op.add_column('user', sa.Column('gender', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('phone_number', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('updated_on', sa.DateTime(), nullable=False))
    op.drop_column('user', 'registered_on')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('registered_on', mysql.DATETIME(), nullable=False))
    op.drop_column('user', 'updated_on')
    op.drop_column('user', 'phone_number')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'full_name')
    op.drop_column('user', 'date_of_birth')
    op.drop_column('user', 'created_on')
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###
