"""Update migration

Revision ID: 753be1d48196
Revises: 51f4af90bb15
Create Date: 2021-02-17 20:53:35.471450

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '753be1d48196'
down_revision = '51f4af90bb15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('user_public_id', sa.String(length=100), nullable=False))
    op.alter_column('settings', 'address',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=True)
    op.alter_column('settings', 'billing_address',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=True)
    op.alter_column('settings', 'created_on',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('settings', 'email',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=True)
    op.alter_column('settings', 'fax_number',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=True)
    op.alter_column('settings', 'full_name',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=True)
    op.alter_column('settings', 'phone_number',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=True)
    op.alter_column('settings', 'updated_on',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('settings', 'updated_on',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('settings', 'phone_number',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=False)
    op.alter_column('settings', 'full_name',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=False)
    op.alter_column('settings', 'fax_number',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=False)
    op.alter_column('settings', 'email',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=False)
    op.alter_column('settings', 'created_on',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('settings', 'billing_address',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=False)
    op.alter_column('settings', 'address',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=False)
    op.drop_column('settings', 'user_public_id')
    # ### end Alembic commands ###
