"""Update migration

Revision ID: 78fe7f7528bb
Revises: b2e854c0e38e
Create Date: 2020-11-06 11:12:12.614982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78fe7f7528bb'
down_revision = 'b2e854c0e38e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_price_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_price', sa.Numeric(), nullable=False),
    sa.Column('sale_price', sa.Numeric(), nullable=False),
    sa.Column('price_updated_date', sa.DateTime(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_price_history')
    # ### end Alembic commands ###
