"""Update migration

Revision ID: d22345c76f95
Revises: d26e9e59469b
Create Date: 2021-02-01 09:51:50.610795

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd22345c76f95'
down_revision = 'd26e9e59469b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('title', table_name='recommended_list')
    op.drop_table('recommended_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommended_list',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=False),
    sa.Column('description', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=False),
    sa.Column('total_products', mysql.DECIMAL(precision=10, scale=0), nullable=False),
    sa.Column('time_span', mysql.DATETIME(), nullable=False),
    sa.Column('created_on', mysql.DATETIME(), nullable=False),
    sa.Column('updated_on', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('title', 'recommended_list', ['title'], unique=True)
    # ### end Alembic commands ###
