"""Update migration

Revision ID: f4e8eee02351
Revises: 9052c9914763
Create Date: 2021-02-17 06:15:17.886014

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f4e8eee02351'
down_revision = '9052c9914763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('fax_number', sa.String(length=255), nullable=False))
    op.alter_column('transaction_list', 'total_amount',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction_list', 'total_amount',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               nullable=False)
    op.drop_column('settings', 'fax_number')
    # ### end Alembic commands ###
