"""Update migration

Revision ID: f83f2db62ecb
Revises: d22345c76f95
Create Date: 2021-02-01 14:29:33.090746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f83f2db62ecb'
down_revision = 'd22345c76f95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommended_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('total_products', sa.Numeric(), nullable=False),
    sa.Column('time_span_month', sa.Numeric(), nullable=False),
    sa.Column('time_span_year', sa.Numeric(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('recommended_list_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('recommended_list_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.Column('min_quantity', sa.Numeric(), nullable=False),
    sa.Column('max_quantity', sa.Numeric(), nullable=False),
    sa.Column('revenue', sa.Numeric(), nullable=False),
    sa.Column('min_revenue', sa.Numeric(), nullable=False),
    sa.Column('max_revenue', sa.Numeric(), nullable=False),
    sa.Column('accuracy', sa.Numeric(), nullable=False),
    sa.Column('priority', sa.Numeric(), nullable=False),
    sa.Column('original_price', sa.Numeric(), nullable=False),
    sa.Column('sale_price', sa.Numeric(), nullable=False),
    sa.Column('profit_rate', sa.Numeric(), nullable=False),
    sa.Column('inware_amount', sa.Numeric(), nullable=False),
    sa.Column('min_inware_amount', sa.Numeric(), nullable=False),
    sa.Column('max_inware_amount', sa.Numeric(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['recommended_list_id'], ['recommended_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommended_list_item')
    op.drop_table('recommended_list')
    # ### end Alembic commands ###
